# Generated by Django 3.2.8 on 2021-10-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='photo_description',
            field=models.CharField(max_length=500),
        ),
    ]
