# Generated by Django 3.2.8 on 2021-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_alter_photomodel_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='photo_description',
            field=models.TextField(max_length=500),
        ),
    ]
